// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fuzzer_interface.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff9b483743270f, []int{0}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type StringMap struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMap) Reset()         { *m = StringMap{} }
func (m *StringMap) String() string { return proto.CompactTextString(m) }
func (*StringMap) ProtoMessage()    {}
func (*StringMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff9b483743270f, []int{1}
}

func (m *StringMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMap.Unmarshal(m, b)
}
func (m *StringMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMap.Marshal(b, m, deterministic)
}
func (m *StringMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMap.Merge(m, src)
}
func (m *StringMap) XXX_Size() int {
	return xxx_messageInfo_StringMap.Size(m)
}
func (m *StringMap) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMap.DiscardUnknown(m)
}

var xxx_messageInfo_StringMap proto.InternalMessageInfo

func (m *StringMap) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StringMap) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PrepareArg struct {
	CorpusDir            string            `protobuf:"bytes,1,opt,name=corpusDir,proto3" json:"corpusDir,omitempty"`
	TargetPath           string            `protobuf:"bytes,2,opt,name=targetPath,proto3" json:"targetPath,omitempty"`
	Arguments            map[string]string `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Environments         []string          `protobuf:"bytes,4,rep,name=environments,proto3" json:"environments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PrepareArg) Reset()         { *m = PrepareArg{} }
func (m *PrepareArg) String() string { return proto.CompactTextString(m) }
func (*PrepareArg) ProtoMessage()    {}
func (*PrepareArg) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff9b483743270f, []int{2}
}

func (m *PrepareArg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareArg.Unmarshal(m, b)
}
func (m *PrepareArg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareArg.Marshal(b, m, deterministic)
}
func (m *PrepareArg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareArg.Merge(m, src)
}
func (m *PrepareArg) XXX_Size() int {
	return xxx_messageInfo_PrepareArg.Size(m)
}
func (m *PrepareArg) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareArg.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareArg proto.InternalMessageInfo

func (m *PrepareArg) GetCorpusDir() string {
	if m != nil {
		return m.CorpusDir
	}
	return ""
}

func (m *PrepareArg) GetTargetPath() string {
	if m != nil {
		return m.TargetPath
	}
	return ""
}

func (m *PrepareArg) GetArguments() map[string]string {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *PrepareArg) GetEnvironments() []string {
	if m != nil {
		return m.Environments
	}
	return nil
}

type FuzzArg struct {
	MaxTime              int32    `protobuf:"varint,1,opt,name=maxTime,proto3" json:"maxTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FuzzArg) Reset()         { *m = FuzzArg{} }
func (m *FuzzArg) String() string { return proto.CompactTextString(m) }
func (*FuzzArg) ProtoMessage()    {}
func (*FuzzArg) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff9b483743270f, []int{3}
}

func (m *FuzzArg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuzzArg.Unmarshal(m, b)
}
func (m *FuzzArg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuzzArg.Marshal(b, m, deterministic)
}
func (m *FuzzArg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuzzArg.Merge(m, src)
}
func (m *FuzzArg) XXX_Size() int {
	return xxx_messageInfo_FuzzArg.Size(m)
}
func (m *FuzzArg) XXX_DiscardUnknown() {
	xxx_messageInfo_FuzzArg.DiscardUnknown(m)
}

var xxx_messageInfo_FuzzArg proto.InternalMessageInfo

func (m *FuzzArg) GetMaxTime() int32 {
	if m != nil {
		return m.MaxTime
	}
	return 0
}

type Crash struct {
	InputPath            string   `protobuf:"bytes,1,opt,name=inputPath,proto3" json:"inputPath,omitempty"`
	ReproduceArg         []string `protobuf:"bytes,2,rep,name=reproduceArg,proto3" json:"reproduceArg,omitempty"`
	Environments         []string `protobuf:"bytes,3,rep,name=environments,proto3" json:"environments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Crash) Reset()         { *m = Crash{} }
func (m *Crash) String() string { return proto.CompactTextString(m) }
func (*Crash) ProtoMessage()    {}
func (*Crash) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff9b483743270f, []int{4}
}

func (m *Crash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Crash.Unmarshal(m, b)
}
func (m *Crash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Crash.Marshal(b, m, deterministic)
}
func (m *Crash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Crash.Merge(m, src)
}
func (m *Crash) XXX_Size() int {
	return xxx_messageInfo_Crash.Size(m)
}
func (m *Crash) XXX_DiscardUnknown() {
	xxx_messageInfo_Crash.DiscardUnknown(m)
}

var xxx_messageInfo_Crash proto.InternalMessageInfo

func (m *Crash) GetInputPath() string {
	if m != nil {
		return m.InputPath
	}
	return ""
}

func (m *Crash) GetReproduceArg() []string {
	if m != nil {
		return m.ReproduceArg
	}
	return nil
}

func (m *Crash) GetEnvironments() []string {
	if m != nil {
		return m.Environments
	}
	return nil
}

type FuzzResult struct {
	Command              []string          `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	Crashes              []*Crash          `protobuf:"bytes,2,rep,name=crashes,proto3" json:"crashes,omitempty"`
	Stats                map[string]string `protobuf:"bytes,3,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TimeExecuted         int32             `protobuf:"varint,4,opt,name=timeExecuted,proto3" json:"timeExecuted,omitempty"`
	Error                string            `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FuzzResult) Reset()         { *m = FuzzResult{} }
func (m *FuzzResult) String() string { return proto.CompactTextString(m) }
func (*FuzzResult) ProtoMessage()    {}
func (*FuzzResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff9b483743270f, []int{5}
}

func (m *FuzzResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuzzResult.Unmarshal(m, b)
}
func (m *FuzzResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuzzResult.Marshal(b, m, deterministic)
}
func (m *FuzzResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuzzResult.Merge(m, src)
}
func (m *FuzzResult) XXX_Size() int {
	return xxx_messageInfo_FuzzResult.Size(m)
}
func (m *FuzzResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FuzzResult.DiscardUnknown(m)
}

var xxx_messageInfo_FuzzResult proto.InternalMessageInfo

func (m *FuzzResult) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *FuzzResult) GetCrashes() []*Crash {
	if m != nil {
		return m.Crashes
	}
	return nil
}

func (m *FuzzResult) GetStats() map[string]string {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *FuzzResult) GetTimeExecuted() int32 {
	if m != nil {
		return m.TimeExecuted
	}
	return 0
}

func (m *FuzzResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ReproduceArg struct {
	InputPath            string   `protobuf:"bytes,1,opt,name=inputPath,proto3" json:"inputPath,omitempty"`
	MaxTime              int32    `protobuf:"varint,2,opt,name=maxTime,proto3" json:"maxTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReproduceArg) Reset()         { *m = ReproduceArg{} }
func (m *ReproduceArg) String() string { return proto.CompactTextString(m) }
func (*ReproduceArg) ProtoMessage()    {}
func (*ReproduceArg) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff9b483743270f, []int{6}
}

func (m *ReproduceArg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReproduceArg.Unmarshal(m, b)
}
func (m *ReproduceArg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReproduceArg.Marshal(b, m, deterministic)
}
func (m *ReproduceArg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReproduceArg.Merge(m, src)
}
func (m *ReproduceArg) XXX_Size() int {
	return xxx_messageInfo_ReproduceArg.Size(m)
}
func (m *ReproduceArg) XXX_DiscardUnknown() {
	xxx_messageInfo_ReproduceArg.DiscardUnknown(m)
}

var xxx_messageInfo_ReproduceArg proto.InternalMessageInfo

func (m *ReproduceArg) GetInputPath() string {
	if m != nil {
		return m.InputPath
	}
	return ""
}

func (m *ReproduceArg) GetMaxTime() int32 {
	if m != nil {
		return m.MaxTime
	}
	return 0
}

type ReproduceResult struct {
	Command              []string `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	ReturnCode           int32    `protobuf:"varint,2,opt,name=returnCode,proto3" json:"returnCode,omitempty"`
	TimeExecuted         int32    `protobuf:"varint,3,opt,name=timeExecuted,proto3" json:"timeExecuted,omitempty"`
	Output               []string `protobuf:"bytes,4,rep,name=output,proto3" json:"output,omitempty"`
	Error                string   `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReproduceResult) Reset()         { *m = ReproduceResult{} }
func (m *ReproduceResult) String() string { return proto.CompactTextString(m) }
func (*ReproduceResult) ProtoMessage()    {}
func (*ReproduceResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff9b483743270f, []int{7}
}

func (m *ReproduceResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReproduceResult.Unmarshal(m, b)
}
func (m *ReproduceResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReproduceResult.Marshal(b, m, deterministic)
}
func (m *ReproduceResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReproduceResult.Merge(m, src)
}
func (m *ReproduceResult) XXX_Size() int {
	return xxx_messageInfo_ReproduceResult.Size(m)
}
func (m *ReproduceResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ReproduceResult.DiscardUnknown(m)
}

var xxx_messageInfo_ReproduceResult proto.InternalMessageInfo

func (m *ReproduceResult) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *ReproduceResult) GetReturnCode() int32 {
	if m != nil {
		return m.ReturnCode
	}
	return 0
}

func (m *ReproduceResult) GetTimeExecuted() int32 {
	if m != nil {
		return m.TimeExecuted
	}
	return 0
}

func (m *ReproduceResult) GetOutput() []string {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *ReproduceResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff9b483743270f, []int{8}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ErrorResponse)(nil), "proto.ErrorResponse")
	proto.RegisterType((*StringMap)(nil), "proto.StringMap")
	proto.RegisterType((*PrepareArg)(nil), "proto.PrepareArg")
	proto.RegisterMapType((map[string]string)(nil), "proto.PrepareArg.ArgumentsEntry")
	proto.RegisterType((*FuzzArg)(nil), "proto.FuzzArg")
	proto.RegisterType((*Crash)(nil), "proto.Crash")
	proto.RegisterType((*FuzzResult)(nil), "proto.FuzzResult")
	proto.RegisterMapType((map[string]string)(nil), "proto.FuzzResult.StatsEntry")
	proto.RegisterType((*ReproduceArg)(nil), "proto.ReproduceArg")
	proto.RegisterType((*ReproduceResult)(nil), "proto.ReproduceResult")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
}

func init() { proto.RegisterFile("fuzzer_interface.proto", fileDescriptor_41ff9b483743270f) }

var fileDescriptor_41ff9b483743270f = []byte{
	// 527 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0x45, 0x96, 0x65, 0xa3, 0x89, 0x9b, 0x36, 0xdb, 0x60, 0x84, 0x09, 0xc1, 0xa8, 0xb4, 0xb8,
	0x14, 0x7c, 0x70, 0x2e, 0xa6, 0x94, 0x42, 0x70, 0xed, 0x5b, 0x21, 0x28, 0xbd, 0x97, 0xad, 0x3c,
	0x71, 0x44, 0xad, 0x95, 0x18, 0xed, 0x86, 0xd8, 0xff, 0xa5, 0x7f, 0xa9, 0xbf, 0xa4, 0xe7, 0x9e,
	0xcb, 0xae, 0x56, 0x96, 0x5c, 0x9b, 0x7e, 0x9c, 0xa4, 0x79, 0x3b, 0x33, 0xfb, 0xde, 0x9b, 0x1d,
	0xe8, 0xdf, 0xa9, 0xed, 0x16, 0xe9, 0x73, 0x22, 0x24, 0xd2, 0x1d, 0x8f, 0x71, 0x9c, 0x53, 0x26,
	0x33, 0xe6, 0x99, 0x4f, 0xf8, 0x12, 0x9e, 0xcc, 0x89, 0x32, 0x8a, 0xb0, 0xc8, 0x33, 0x51, 0x20,
	0x3b, 0x07, 0x0f, 0x35, 0x10, 0x38, 0x43, 0x67, 0xe4, 0x47, 0x65, 0x10, 0x5e, 0x81, 0x7f, 0x2b,
	0x29, 0x11, 0xab, 0x8f, 0x3c, 0x67, 0xcf, 0xc0, 0xfd, 0x8a, 0x1b, 0x9b, 0xa0, 0x7f, 0x75, 0xd1,
	0x03, 0x5f, 0x2b, 0x0c, 0x5a, 0x65, 0x91, 0x09, 0xc2, 0x1f, 0x0e, 0xc0, 0x0d, 0x61, 0xce, 0x09,
	0xaf, 0x69, 0xc5, 0x2e, 0xc0, 0x8f, 0x33, 0xca, 0x55, 0xf1, 0x21, 0xa9, 0xba, 0xd7, 0x00, 0xbb,
	0x04, 0x90, 0x9c, 0x56, 0x28, 0x6f, 0xb8, 0xbc, 0xb7, 0x7d, 0x1a, 0x08, 0x7b, 0x0f, 0x3e, 0xa7,
	0x95, 0x4a, 0x51, 0xc8, 0x22, 0x70, 0x87, 0xee, 0xe8, 0x64, 0x32, 0x2c, 0xa5, 0x8c, 0xeb, 0x3b,
	0xc6, 0xd7, 0x55, 0xca, 0x5c, 0x48, 0xda, 0x44, 0x75, 0x09, 0x0b, 0xa1, 0x87, 0xe2, 0x21, 0xa1,
	0x4c, 0x94, 0x2d, 0xda, 0x43, 0x77, 0xe4, 0x47, 0x7b, 0xd8, 0xe0, 0x1d, 0x9c, 0xee, 0x37, 0xf8,
	0x57, 0xa9, 0x6f, 0x5b, 0x53, 0x27, 0x7c, 0x01, 0xdd, 0x85, 0xda, 0x6e, 0xb5, 0xd4, 0x00, 0xba,
	0x29, 0x7f, 0xfc, 0x94, 0xa4, 0x68, 0x4a, 0xbd, 0xa8, 0x0a, 0xc3, 0x14, 0xbc, 0x19, 0xf1, 0xe2,
	0x5e, 0xbb, 0x91, 0x88, 0x5c, 0x95, 0x72, 0xad, 0x1b, 0x3b, 0x40, 0xb3, 0x25, 0xcc, 0x29, 0x5b,
	0xaa, 0x58, 0xeb, 0x0a, 0x5a, 0x25, 0xdb, 0x26, 0x76, 0xa0, 0xc8, 0x3d, 0x54, 0x14, 0xfe, 0x74,
	0x00, 0x34, 0xa9, 0x08, 0x0b, 0xb5, 0x96, 0x9a, 0x57, 0x9c, 0xa5, 0x29, 0x17, 0xcb, 0xc0, 0x31,
	0xd9, 0x55, 0xc8, 0x5e, 0x41, 0x37, 0xd6, 0xbc, 0xb0, 0x30, 0x77, 0x9d, 0x4c, 0x7a, 0xd6, 0x5c,
	0xc3, 0x36, 0xaa, 0x0e, 0xd9, 0x04, 0xbc, 0x42, 0xf2, 0xdd, 0x08, 0x2e, 0x6c, 0x56, 0x7d, 0xc7,
	0xf8, 0x56, 0x1f, 0x97, 0xf6, 0x97, 0xa9, 0x9a, 0xa8, 0x4c, 0x52, 0x9c, 0x3f, 0x62, 0xac, 0x24,
	0x2e, 0x83, 0xb6, 0xb1, 0x64, 0x0f, 0xab, 0x9f, 0x9d, 0xd7, 0x78, 0x76, 0x83, 0x29, 0x40, 0xdd,
	0xee, 0xbf, 0x86, 0xb1, 0x80, 0x5e, 0xd4, 0x34, 0xeb, 0xcf, 0x76, 0x37, 0xe6, 0xd5, 0xda, 0x9f,
	0xd7, 0x37, 0x07, 0x9e, 0xee, 0x1a, 0xfd, 0xd5, 0xc5, 0x4b, 0x00, 0x42, 0xa9, 0x48, 0xcc, 0xb2,
	0x65, 0xd5, 0xaa, 0x81, 0x1c, 0x38, 0xe1, 0x1e, 0x71, 0xa2, 0x0f, 0x9d, 0x4c, 0xc9, 0x5c, 0x49,
	0xfb, 0x44, 0x6d, 0x74, 0xdc, 0xa1, 0xb0, 0x0b, 0xde, 0x3c, 0xcd, 0xe5, 0x66, 0xf2, 0xdd, 0x81,
	0xce, 0xc2, 0xac, 0x3a, 0x9b, 0x40, 0xd7, 0xae, 0x04, 0x3b, 0x3b, 0x58, 0x91, 0xc1, 0xb9, 0x85,
	0xf6, 0xd7, 0xfe, 0x35, 0xb4, 0x75, 0x35, 0x3b, 0x6d, 0x0c, 0x54, 0x67, 0x9f, 0x1d, 0x0c, 0x98,
	0x4d, 0xc1, 0xdf, 0x39, 0xc2, 0x9e, 0xdb, 0xf3, 0xa6, 0xd9, 0x83, 0xfe, 0xef, 0xa0, 0xad, 0x7c,
	0x03, 0xde, 0x6c, 0x8d, 0x5c, 0xb0, 0xea, 0x71, 0x19, 0xea, 0xc7, 0x19, 0x7d, 0xe9, 0x18, 0xf0,
	0xea, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x63, 0x99, 0x89, 0xc1, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FuzzerClient is the client API for Fuzzer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FuzzerClient interface {
	Prepare(ctx context.Context, in *PrepareArg, opts ...grpc.CallOption) (*ErrorResponse, error)
	Fuzz(ctx context.Context, in *FuzzArg, opts ...grpc.CallOption) (*FuzzResult, error)
	Reproduce(ctx context.Context, in *ReproduceArg, opts ...grpc.CallOption) (*ReproduceResult, error)
	Clean(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ErrorResponse, error)
}

type fuzzerClient struct {
	cc *grpc.ClientConn
}

func NewFuzzerClient(cc *grpc.ClientConn) FuzzerClient {
	return &fuzzerClient{cc}
}

func (c *fuzzerClient) Prepare(ctx context.Context, in *PrepareArg, opts ...grpc.CallOption) (*ErrorResponse, error) {
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, "/proto.Fuzzer/Prepare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fuzzerClient) Fuzz(ctx context.Context, in *FuzzArg, opts ...grpc.CallOption) (*FuzzResult, error) {
	out := new(FuzzResult)
	err := c.cc.Invoke(ctx, "/proto.Fuzzer/Fuzz", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fuzzerClient) Reproduce(ctx context.Context, in *ReproduceArg, opts ...grpc.CallOption) (*ReproduceResult, error) {
	out := new(ReproduceResult)
	err := c.cc.Invoke(ctx, "/proto.Fuzzer/Reproduce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fuzzerClient) Clean(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ErrorResponse, error) {
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, "/proto.Fuzzer/Clean", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FuzzerServer is the server API for Fuzzer service.
type FuzzerServer interface {
	Prepare(context.Context, *PrepareArg) (*ErrorResponse, error)
	Fuzz(context.Context, *FuzzArg) (*FuzzResult, error)
	Reproduce(context.Context, *ReproduceArg) (*ReproduceResult, error)
	Clean(context.Context, *Empty) (*ErrorResponse, error)
}

// UnimplementedFuzzerServer can be embedded to have forward compatible implementations.
type UnimplementedFuzzerServer struct {
}

func (*UnimplementedFuzzerServer) Prepare(ctx context.Context, req *PrepareArg) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (*UnimplementedFuzzerServer) Fuzz(ctx context.Context, req *FuzzArg) (*FuzzResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fuzz not implemented")
}
func (*UnimplementedFuzzerServer) Reproduce(ctx context.Context, req *ReproduceArg) (*ReproduceResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reproduce not implemented")
}
func (*UnimplementedFuzzerServer) Clean(ctx context.Context, req *Empty) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Clean not implemented")
}

func RegisterFuzzerServer(s *grpc.Server, srv FuzzerServer) {
	s.RegisterService(&_Fuzzer_serviceDesc, srv)
}

func _Fuzzer_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FuzzerServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Fuzzer/Prepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FuzzerServer).Prepare(ctx, req.(*PrepareArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fuzzer_Fuzz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FuzzArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FuzzerServer).Fuzz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Fuzzer/Fuzz",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FuzzerServer).Fuzz(ctx, req.(*FuzzArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fuzzer_Reproduce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReproduceArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FuzzerServer).Reproduce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Fuzzer/Reproduce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FuzzerServer).Reproduce(ctx, req.(*ReproduceArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fuzzer_Clean_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FuzzerServer).Clean(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Fuzzer/Clean",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FuzzerServer).Clean(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Fuzzer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Fuzzer",
	HandlerType: (*FuzzerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _Fuzzer_Prepare_Handler,
		},
		{
			MethodName: "Fuzz",
			Handler:    _Fuzzer_Fuzz_Handler,
		},
		{
			MethodName: "Reproduce",
			Handler:    _Fuzzer_Reproduce_Handler,
		},
		{
			MethodName: "Clean",
			Handler:    _Fuzzer_Clean_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fuzzer_interface.proto",
}
