server: 
        runMode: debug
        port: 8888
        readTimeout: 60
        writeTimeout: 60
        tempPath: /tmp
        uploadFileLimit: 80
        defaultFuzzerName: fuzzer
        defaultFuzzTime: 86400
        defaultReproduceTime: 10
