server: 
        runMode: debug
        port: 8889
        readTimeout: 60
        writeTimeout: 60
        tempPath: /tmp
        crashesPath: ./crashes

kubernetes:
        configPath: ""
        namespace: "cfuzz"
        checkTaskTime: 10
        maxClientRetryNum: 30
