kubernetes:
  checktasktime: 10
  configpath: ""
  initcleanup: false
  maxclientretrynum: 10
  maxstarttime: 3600
  namespace: cfuzz
  requesttimeout: 60
server:
  runmode: debug
  port: 8889
  readtimeout: "60"
  writetimeout: "60"
  temppath: /tmp
  crashespath: ./crashes
  logtofile: true
  logfiledir: /tmp
  signingkey: 2h5x61zNg1
